First round of review changes
hchen139/moose pull request #2
Opened 2018-09-27 21:28 UTC by bwspenc

ref #11561

2018-09-27 21:31 UTC, bwspenc commented
@hchen139 As I'm going through this code, I think it will be easier for me to just make the changes in many cases, so I'd like to try this approach out.  I can submit proposed changes, and you can merge them into your branch if you agree with them.

2018-09-27 21:32 UTC, bwspenc commented on modules/peridynamics/src/auxkernels/BondStatusPD.C
> -  MooseEnum FailureCriteriaType("Critical_Stretch Maximum_Tensile_Stress", "Critical_Stretch");
A comment here:  I changed these names to be more consistent with MOOSE conventions.  I expected to break a test when I did that, but this is apparently not tested.

2018-09-27 21:34 UTC, bwspenc commented on modules/peridynamics/src/auxkernels/MechanicalStretchPD.C
>    params.set<ExecFlagEnum>("execute_on") = EXEC_TIMESTEP_END;
Can't you just use MaterialRealAux for this purpose?  Also, I'm a little hesitant about setting a nonstandard value for 'execute_on' -- if the user wants it just for output purposes, I think I would expect them to set this.

2018-09-28 00:20 UTC, hchen139 requested changes

2018-09-28 00:20 UTC, hchen139 commented on modules/peridynamics/include/auxkernels/BondStatusPD.h
> +    MaximumTensileStress
The correct available failure criterion name should be CriticalStretch and MaximumPrincipalStress. This is a bug in the original code.

2018-09-28 00:20 UTC, hchen139 commented on modules/peridynamics/src/auxkernels/BondStatusPD.C
> -  MooseEnum FailureCriteriaType("Critical_Stretch Maximum_Tensile_Stress", "Critical_Stretch");
This code has not been tested, i.e., there is no corresponding regression test. We don't really have a test for crack propagation problem.

2018-09-28 00:20 UTC, hchen139 commented on modules/peridynamics/src/auxkernels/BondStatusPD.C
> +  MooseEnum FailureCriteriaType("CriticalStretch MaximumTensileStress", "CriticalStretch");
Again, we need to use MaximumPrincipalStress rather than MaximumTensileStress.

2018-09-28 00:20 UTC, hchen139 commented on modules/peridynamics/src/auxkernels/BondStatusPD.C
> +    case FailureCriterion::MaximumTensileStress:
FailureCriterion::MaximumPrincipalStress

2018-09-28 00:20 UTC, hchen139 commented on modules/peridynamics/src/auxkernels/BondStatusPD.C
> +    case FailureCriterion::MaximumTensileStress:
FailureCriterion::MaximumPrincipalStress

2018-09-28 00:20 UTC, hchen139 commented on modules/peridynamics/src/auxkernels/MechanicalStretchPD.C
>    params.set<ExecFlagEnum>("execute_on") = EXEC_TIMESTEP_END;
The MaterialRealAux outputs element volume-averaged material properties. There are some calculations related to volume and I'm sure whether they can be directly applied to Edge2 element. You are right, since the purpose of this AuxKernel is to output the bond mechanical stretch, it should be the user's decision to set the output frequency as they want.

2018-09-28 00:23 UTC, hchen139 commented
@bwspenc Agree. Let's work on making changes on my local branch rather than submit small changes directly to MOOSE.

2018-10-09 01:17 UTC, merged

2018-10-09 01:19 UTC, hchen139 commented
I merged this pull request so that I can work on to address those issue myself.